In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [3]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()  
df = pd.read_csv(f'../landing/{arquivo}', sep=";") 
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100   2000  z0019_2.csv 2026-07-31 17:26:25.893131
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-07-31 17:26:25.893131
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-07-31 17:26:25.893131

In [4]:
con.execute('''
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )
''')

In [5]:
con.execute('INSERT INTO bronze_produtos SELECT * FROM df')

In [9]:
resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head(20)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-31 17:04:28.395855
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-31 17:04:28.395855
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-07-31 17:04:28.395855
3  10004     SERRA  BT50   100  2000  z0019_2.csv 2026-07-31 17:04:41.909185
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-31 17:04:41.909185
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-07-31 17:04:41.909185

In [7]:
con.execute('ALTER TABLE bronze_produtos RENAME TO bronze_z0019')

CatalogException: Catalog Error: Could not rename "bronze_produtos" to "bronze_z0019": another entry with this name already exists!

In [11]:
con.close()

In [10]:
resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head(20)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-31 17:04:28.395855
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-31 17:04:28.395855
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-07-31 17:04:28.395855
3  10004     SERRA  BT50   100  2000  z0019_2.csv 2026-07-31 17:04:41.909185
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-31 17:04:41.909185
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-07-31 17:04:41.909185