In [4]:
import duckdb

In [5]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [12]:
df = con.execute("SELECT * FROM produtos").fetchdf()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10004      SERRA         BT50            100    2000.0
3  10005    MACHADO         BT50            100     100.0
4  10003      PREGO         BT10            100      60.0

In [37]:
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])

df2.head(10)

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO    1500.0
2  10004      SERRA    2000.0
3  10005    MACHADO     100.0
4  10003      PREGO      60.0

In [22]:
con.execute('''DROP TABLE IF EXISTS dim_produtos''')

In [38]:
con.execute('''
    CREATE TABLE IF NOT EXISTS dim_produtos (
        id_produto BIGINT,
        nm_produto TEXT,
        vl_produto FLOAT
    )
''')

In [39]:
con.execute("INSERT INTO dim_produtos SELECT * FROM df2")

In [40]:
df_din = con.execute('SELECT * FROM dim_produtos').fetchdf()
df_din.head(10)

   id_produto nm_produto  vl_produto
0       10001   PARAFUSO       100.0
1       10002    MARTELO      1500.0
2       10004      SERRA      2000.0
3       10005    MACHADO       100.0
4       10003      PREGO        60.0
5       10001   PARAFUSO       100.0
6       10002    MARTELO      1500.0
7       10004      SERRA      2000.0
8       10005    MACHADO       100.0
9       10003      PREGO        60.0

In [41]:
con.close()